name: Lint/Test

on:
    [workflow_dispatch, push]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ latest ]

        steps:
            -   uses: actions/checkout@master
            
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@master
                with:
                    node-version: ${{ matrix.node-version }}
           
            -   name: uh oh
                run: echo $NODE_PATH

            -   name: Install dependencies
                run: npm ci

            -   name: Run tests
                run: npm test